language: rust
# cargo cache results may vary:
# https://levans.fr/rust_travis_cache.html
#cache: cargo

rust:
    - stable
    - nightly

# Allow nightly failures.
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

env:
    global:
        - RUST_BACKTRACE=1
        # Limit to just one thread (helpful for test races)
        #- RUST_TEST_THREADS=1

cache: cargo

#script:
    - cargo fmt -- --check
    # build all projects, except foo
    # *NOTE* `foo` is the Cargo.toml package name, not the directory.
    #- cargo build --all --exclude=foo

notifications:
    email: false
